//! Portable path resolution (A read package / B work root).
//! Order matches former agent_on_paths.py.

use regex::Regex;
use serde_json::Value;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

pub const MARKERS: &[&str] = &["CHARTER.md", "BOOTSTRAP.md"];
pub const LOCK_NAME: &str = "agent-on.lock.md";
pub const OFFICIAL_HTTPS: &str = "https://github.com/Palebluedot-ai/agent-on.git";
pub const DEFAULT_PIN: &str = "v0.7.1";

pub fn expand(p: &str) -> PathBuf {
    let t = p.trim().trim_matches(|c| c == '"' || c == '\'');
    let expanded = if t.starts_with("~/") || t == "~" {
        let home = dirs_home();
        if t == "~" {
            home
        } else {
            home.join(&t[2..])
        }
    } else {
        PathBuf::from(t)
    };
    fs::canonicalize(&expanded).unwrap_or(expanded)
}

fn dirs_home() -> PathBuf {
    env::var_os("HOME")
        .or_else(|| env::var_os("USERPROFILE"))
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("."))
}

pub fn default_work_root() -> PathBuf {
    if cfg!(windows) {
        if let Ok(base) = env::var("LOCALAPPDATA") {
            return PathBuf::from(base).join("agent-on");
        }
        return dirs_home()
            .join("AppData")
            .join("Local")
            .join("agent-on");
    }
    dirs_home().join(".local").join("share").join("agent-on")
}

pub fn looks_like_agent_on(root: &Path) -> bool {
    if !root.is_dir() {
        return false;
    }
    MARKERS.iter().all(|m| root.join(m).is_file())
}

pub fn config_path() -> PathBuf {
    dirs_home().join(".config").join("agent-on").join("config.json")
}

pub fn read_config_work_root() -> Option<PathBuf> {
    let cfg = config_path();
    if !cfg.is_file() {
        return None;
    }
    let text = fs::read_to_string(&cfg).ok()?;
    let data: Value = serde_json::from_str(&text).ok()?;
    let wr = data.get("work_root")?.as_str()?;
    if wr.trim().is_empty() {
        return None;
    }
    Some(expand(wr))
}

pub fn write_config_work_root(work_root: &Path) -> std::io::Result<PathBuf> {
    let cfg = config_path();
    if let Some(parent) = cfg.parent() {
        fs::create_dir_all(parent)?;
    }
    let resolved = fs::canonicalize(work_root).unwrap_or_else(|_| work_root.to_path_buf());
    let payload = serde_json::json!({
        "work_root": resolved.to_string_lossy(),
        "default_layout": "v1",
        "note": "Generated by agent-on setup; AGENT_ON_ROOT overrides this.",
    });
    fs::write(&cfg, format!("{}\n", serde_json::to_string_pretty(&payload)?))?;
    Ok(cfg)
}

pub fn find_lock_up(start: Option<&Path>) -> Option<PathBuf> {
    let mut cur = start
        .map(|p| p.to_path_buf())
        .unwrap_or_else(|| env::current_dir().unwrap_or_else(|_| PathBuf::from(".")));
    if let Ok(c) = fs::canonicalize(&cur) {
        cur = c;
    }
    for _ in 0..24 {
        let cand = cur.join(LOCK_NAME);
        if cand.is_file() {
            return Some(cand);
        }
        let parent = cur.parent()?;
        if parent == cur {
            break;
        }
        cur = parent.to_path_buf();
    }
    None
}

pub fn work_root_from_lock(lock_file: &Path) -> Option<PathBuf> {
    let text = fs::read_to_string(lock_file).ok()?;
    let re = Regex::new(r"(?m)^\s*本地路径\s*[:：]\s*`?([^\s`]+)`?\s*$").ok()?;
    let m = re.captures(&text)?;
    Some(expand(m.get(1)?.as_str()))
}

/// Returns (B path or None, source label). Path only if exists and looks like agent-on.
pub fn resolve_work_root(cwd: Option<&Path>) -> (Option<PathBuf>, String) {
    if let Ok(env) = env::var("AGENT_ON_ROOT") {
        if !env.trim().is_empty() {
            let p = expand(&env);
            if looks_like_agent_on(&p) {
                return (Some(p), "AGENT_ON_ROOT".into());
            }
            return (None, "AGENT_ON_ROOT(invalid)".into());
        }
    }

    if let Some(cfg) = read_config_work_root() {
        if looks_like_agent_on(&cfg) {
            return (Some(cfg), "config:work_root".into());
        }
        return (None, "config:work_root(invalid)".into());
    }

    if let Some(lock) = find_lock_up(cwd) {
        if let Some(from_lock) = work_root_from_lock(&lock) {
            if looks_like_agent_on(&from_lock) {
                return (Some(from_lock), format!("lock:{}", lock.display()));
            }
            return (None, format!("lock(invalid):{}", lock.display()));
        }
    }

    let default = default_work_root();
    if looks_like_agent_on(&default) {
        let r = fs::canonicalize(&default).unwrap_or(default);
        return (Some(r), "default_work_root".into());
    }

    (None, "unset".into())
}

pub fn resolve_read_root(cwd: Option<&Path>) -> (Option<PathBuf>, String) {
    for key in ["CLAUDE_PLUGIN_ROOT", "PLUGIN_ROOT"] {
        if let Ok(v) = env::var(key) {
            if !v.trim().is_empty() {
                let p = expand(&v);
                if looks_like_agent_on(&p) {
                    return (Some(p), key.into());
                }
            }
        }
    }
    let (wr, src) = resolve_work_root(cwd);
    if let Some(wr) = wr {
        return (Some(wr), format!("work_root via {src}"));
    }
    (None, "unset".into())
}

pub fn doctor_report(cwd: Option<&Path>) -> String {
    let (rr, rs) = resolve_read_root(cwd);
    let (wr, ws) = resolve_work_root(cwd);
    let dflt = default_work_root();
    let mut lines = vec![
        format!(
            "read_root     = {}  [{}]",
            rr.as_ref()
                .map(|p| p.display().to_string())
                .unwrap_or_else(|| "(none)".into()),
            rs
        ),
        format!(
            "work_root     = {}  [{}]",
            wr.as_ref()
                .map(|p| p.display().to_string())
                .unwrap_or_else(|| "(none)".into()),
            ws
        ),
        format!(
            "default_B     = {}  exists={} valid={}",
            dflt.display(),
            dflt.is_dir(),
            looks_like_agent_on(&dflt)
        ),
        format!(
            "config        = {}  exists={}",
            config_path().display(),
            config_path().is_file()
        ),
    ];
    for k in ["AGENT_ON_ROOT", "CLAUDE_PLUGIN_ROOT", "PLUGIN_ROOT"] {
        lines.push(format!(
            "env {k} = {}",
            env::var(k).unwrap_or_else(|_| "(unset)".into())
        ));
    }
    if wr.is_none() {
        lines.push(String::new());
        lines.push("未登记可写工作仓 (work_root)。init/adopt/handshake 可只靠 plugin。".into());
        lines.push("settle/digest 需要 B。一键：".into());
        lines.push("  agent-on setup".into());
        lines.push(format!("  （将 clone 到默认目录 {} 并写 config）", dflt.display()));
        lines.push("或手动：export AGENT_ON_ROOT=... / 写 config.json / lock 本地路径".into());
    }
    if rr.is_none() {
        lines.push(String::new());
        lines.push("未找到可读运行包。请：".into());
        lines.push("  agent-on setup --with-plugins".into());
        lines.push("  或 claude/codex plugin marketplace add Palebluedot-ai/agent-on && install".into());
    }
    lines.push(String::new());
    lines.join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use std::sync::Mutex;
    use tempfile::tempdir;

    static ENV_LOCK: Mutex<()> = Mutex::new(());

    #[test]
    fn looks_like_requires_markers() {
        let d = tempdir().unwrap();
        assert!(!looks_like_agent_on(d.path()));
        fs::write(d.path().join("CHARTER.md"), "x").unwrap();
        fs::write(d.path().join("BOOTSTRAP.md"), "x").unwrap();
        assert!(looks_like_agent_on(d.path()));
    }

    #[test]
    fn resolve_work_root_env() {
        let _g = ENV_LOCK.lock().unwrap();
        let d = tempdir().unwrap();
        fs::write(d.path().join("CHARTER.md"), "x").unwrap();
        fs::write(d.path().join("BOOTSTRAP.md"), "x").unwrap();
        env::set_var("AGENT_ON_ROOT", d.path());
        let (p, src) = resolve_work_root(None);
        env::remove_var("AGENT_ON_ROOT");
        assert_eq!(src, "AGENT_ON_ROOT");
        assert!(p.is_some());
        assert!(looks_like_agent_on(p.as_ref().unwrap()));
    }

    #[test]
    fn invalid_env_fail_open_style() {
        let _g = ENV_LOCK.lock().unwrap();
        env::set_var("AGENT_ON_ROOT", "/nonexistent/agent-on-xyz");
        let (p, src) = resolve_work_root(None);
        env::remove_var("AGENT_ON_ROOT");
        assert!(p.is_none());
        assert!(src.contains("invalid"));
    }
}
